language: ruby
rvm:
  - 2.0.0p648
env:
  - DB=pgsql

services:
  - postgresql "9.5.2"

script:
  - bundle exec rake db:test:prepare

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

